/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * CLIENT SYMBOL REGISTRY CONSTANTS
 * Authoritative client-side baseline configuration for the 18 active trading instruments:
 * FOREX (10): EURUSD, GBPUSD, USDJPY, USDCHF, AUDUSD, USDCAD, NZDUSD, USDCNH, EURJPY, GBPJPY
 * CRYPTO (5): BTCUSD, ETHUSD, BNBUSD, SOLUSD, XRPUSD
 * COMMODITIES (3): XAUUSD, XAGUSD, WTIUSD
 */

import { SymbolConfig } from '../types/trading';

export const INITIAL_SYMBOLS: SymbolConfig[] = [
  // FOREX (10)
  {
    id: 's_eurusd',
    symbol: 'EURUSD',
    name: 'Euro / US Dollar',
    category: 'FOREX',
    digits: 5,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 1.2,
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
    description: 'Major FX pair with tight institutional spreads.',
  },
  {
    id: 's_gbpusd',
    symbol: 'GBPUSD',
    name: 'British Pound / US Dollar',
    category: 'FOREX',
    digits: 5,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 1.8,
    baseCurrency: 'GBP',
    quoteCurrency: 'USD',
    description: 'Cable: High intraday liquidity and volatility.',
  },
  {
    id: 's_usdjpy',
    symbol: 'USDJPY',
    name: 'US Dollar / Japanese Yen',
    category: 'FOREX',
    digits: 3,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 1.5,
    baseCurrency: 'USD',
    quoteCurrency: 'JPY',
    description: 'Asian session benchmark FX instrument.',
  },
  {
    id: 's_usdchf',
    symbol: 'USDCHF',
    name: 'US Dollar / Swiss Franc',
    category: 'FOREX',
    digits: 5,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 1.5,
    baseCurrency: 'USD',
    quoteCurrency: 'CHF',
    description: 'Safe-haven currency pair.',
  },
  {
    id: 's_audusd',
    symbol: 'AUDUSD',
    name: 'Australian Dollar / USD',
    category: 'FOREX',
    digits: 5,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 1.4,
    baseCurrency: 'AUD',
    quoteCurrency: 'USD',
    description: 'Commodity currency benchmark.',
  },
  {
    id: 's_usdcad',
    symbol: 'USDCAD',
    name: 'US Dollar / Canadian Dollar',
    category: 'FOREX',
    digits: 5,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 1.6,
    baseCurrency: 'USD',
    quoteCurrency: 'CAD',
    description: 'North American trade pair.',
  },
  {
    id: 's_nzdusd',
    symbol: 'NZDUSD',
    name: 'New Zealand Dollar / US Dollar',
    category: 'FOREX',
    digits: 5,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 1.8,
    baseCurrency: 'NZD',
    quoteCurrency: 'USD',
    description: 'Kiwi: Asia-Pacific commodity benchmark.',
  },
  {
    id: 's_usdcnh',
    symbol: 'USDCNH',
    name: 'US Dollar / Chinese Yuan (Offshore)',
    category: 'FOREX',
    digits: 4,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 2.5,
    baseCurrency: 'USD',
    quoteCurrency: 'CNH',
    description: 'Offshore Chinese Yuan / RMB currency instrument.',
  },
  {
    id: 's_eurjpy',
    symbol: 'EURJPY',
    name: 'Euro / Japanese Yen',
    category: 'FOREX',
    digits: 3,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 2.0,
    baseCurrency: 'EUR',
    quoteCurrency: 'JPY',
    description: 'Major cross pair with dynamic trends.',
  },
  {
    id: 's_gbpjpy',
    symbol: 'GBPJPY',
    name: 'British Pound / Japanese Yen',
    category: 'FOREX',
    digits: 3,
    contractSize: 100000,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 2.4,
    baseCurrency: 'GBP',
    quoteCurrency: 'JPY',
    description: 'Geppy: High-volatility cross pair.',
  },

  // CRYPTO (5)
  {
    id: 's_btcusd',
    symbol: 'BTCUSD',
    name: 'Bitcoin / US Dollar',
    category: 'CRYPTO',
    digits: 2,
    contractSize: 1,
    minVolume: 0.01,
    maxVolume: 10.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 120.0,
    baseCurrency: 'BTC',
    quoteCurrency: 'USD',
    description: 'Crypto flagship with 24/7 continuous price action.',
  },
  {
    id: 's_ethusd',
    symbol: 'ETHUSD',
    name: 'Ethereum / US Dollar',
    category: 'CRYPTO',
    digits: 2,
    contractSize: 1,
    minVolume: 0.01,
    maxVolume: 50.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 20.0,
    baseCurrency: 'ETH',
    quoteCurrency: 'USD',
    description: 'Smart contract layer-1 crypto flagship.',
  },
  {
    id: 's_bnbusd',
    symbol: 'BNBUSD',
    name: 'Binance Coin / US Dollar',
    category: 'CRYPTO',
    digits: 2,
    contractSize: 1,
    minVolume: 0.01,
    maxVolume: 50.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 15.0,
    baseCurrency: 'BNB',
    quoteCurrency: 'USD',
    description: 'Binance ecosystem token.',
  },
  {
    id: 's_solusd',
    symbol: 'SOLUSD',
    name: 'Solana / US Dollar',
    category: 'CRYPTO',
    digits: 2,
    contractSize: 1,
    minVolume: 0.01,
    maxVolume: 100.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 10.0,
    baseCurrency: 'SOL',
    quoteCurrency: 'USD',
    description: 'High-throughput layer-1 blockchain.',
  },
  {
    id: 's_xrpusd',
    symbol: 'XRPUSD',
    name: 'Ripple / US Dollar',
    category: 'CRYPTO',
    digits: 4,
    contractSize: 1,
    minVolume: 1.0,
    maxVolume: 10000.0,
    volumeStep: 1.0,
    defaultSpreadPoints: 5.0,
    baseCurrency: 'XRP',
    quoteCurrency: 'USD',
    description: 'Cross-border digital settlement asset.',
  },

  // COMMODITIES (3)
  {
    id: 's_xauusd',
    symbol: 'XAUUSD',
    name: 'Gold (Troy Ounce) / USD',
    category: 'COMMODITIES',
    digits: 2,
    contractSize: 100,
    minVolume: 0.01,
    maxVolume: 50.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 25.0,
    baseCurrency: 'XAU',
    quoteCurrency: 'USD',
    description: 'Spot Gold with high pip value and fast momentum.',
  },
  {
    id: 's_xagusd',
    symbol: 'XAGUSD',
    name: 'Silver (Troy Ounce) / USD',
    category: 'COMMODITIES',
    digits: 3,
    contractSize: 5000,
    minVolume: 0.01,
    maxVolume: 50.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 3.5,
    baseCurrency: 'XAG',
    quoteCurrency: 'USD',
    description: 'Spot Silver with industrial and monetary demand.',
  },
  {
    id: 's_wtiusd',
    symbol: 'WTIUSD',
    name: 'WTI Crude Oil / US Dollar',
    category: 'COMMODITIES',
    digits: 2,
    contractSize: 1000,
    minVolume: 0.01,
    maxVolume: 50.0,
    volumeStep: 0.01,
    defaultSpreadPoints: 4.0,
    baseCurrency: 'WTI',
    quoteCurrency: 'USD',
    description: 'West Texas Intermediate Light Sweet Crude Oil benchmark.',
  },
];

export const ALL_SYMBOLS = [...INITIAL_SYMBOLS];
